name: My_first_action
on: push
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: multi state
        run: |
           echo "hello"
           ls -ltrh
      - name: use shell script
        run: |
           chmod +x shee-example.sh
           ./shell-example.sh
