name: My_first_action
on: workflow_dispatch

env:
   usevar: test
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: multi state
        run: |
           echo "hello"
           ls -ltrh
           touch stage.txt
           echo "${{ secrets.SECRET_NAME }}" > stage.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
           name: upload1
           path: stage.txt
      - name: use shell script
        run: |
           chmod +x shell-example.sh
           ./shell-example.sh
   second_job:
      runs-on: ubuntu-latest
      needs: first_job
      concurrency:
          cancel-in-progress: true
          group: prod
      steps:
      - name: download1
        uses: actions/download-artifact@v4
        with:
           name: upload1
      - name: second stage
        run: |
           echo "hello I am the second job"
           echo "${{ vars.VAR }}"
           cat stage.txt
